spring.application.name=AladinFromSeoul
server.servlet.context-path=/aladin
server.domain=http://localhost:8080
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ssafyhome?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.username=ssafy
spring.datasource.password=ssafy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# mybatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.aladin.**.vo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# email
spring.config.import=optional:application-secret.properties
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.enable=true

# Logging Level Configuration
logging.level.org.mybatis=debug
logging.level.com.aladin=debug

# image store path
file.upload.dir=C:/ssafy/uploads
file.default.profile-image=C:/ssafy/uploads/defaultProfileImage.png
