services:
  mysql:
    image: 'mysql:latest'
    container_name: 'aladdin_mysql'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USERNAME}'
    ports:
      - '3307:3306'
  redis:
    image: 'redis:latest'
    container_name: 'aladdin_redis'
    restart: always
    ports:
      - '6379:6379'
