spring:
  application:
    name: core-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${BASE_URI}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${BASE_URI}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false

logging:
  level:
    root: info
    org.hibernate.SQL: info
      # debug org.hibernate.type: info
    org.hibernate.orm.results: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
